# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 161fb83b61b50faaf2386c3cc3108204d269288d575c6f8ede8e22121d910786c2ae68d317f8c1370456e60fdcd74c42d172007081ebaa87bdbe7c054918a471

test:
  secret_key_base: 5e6a4ead95429d17c29cd096e5dd0c411cbd814316bba238b3a716610b8821071b122feced16e4d940b69bc158c90620bb64c923864f9f9e99dbbe3e8df1c6e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
