# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6fc90a8ca4e19f8070c596a4661f47990cc24e969dc053c5b3f184fa945ee12e917011354ef785014a2dd915396b01f4d31f809bc78cdbbf8a40109e4050714

test:
  secret_key_base: 6ba5bb57526a4b3d58cc26190f8e95824f18c059ae37ca9fe2ffe5c7167f4bda0865a03f2ac6a1170800023d7936cdcdb403908271759356c9446178dca64889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
