# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e13a66c6b6a7fd96785993f21ed89a92b68e4aa15b49eea06f3fe17dcf014fe5a50cc64b0a0f8b578555211b12e19afdd80a683add4e7b7c70fafd77ffe182b5

test:
  secret_key_base: bba5569cd11be1c2b1d8442440f20d8ed9dc92a02eca8f52ae7288d34798f55f899d0d31925a572d5509e594578ee5c954962f015c04b671043d73a27e66d797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
