# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117d3ce586c278ad0f3d9a8bf39c2d93805f42f36a4ce9badd45899bf3617648365b9b0ee51749b44e81bef6c4a86b442274324416d3e6fd66a25b05d6e99465

test:
  secret_key_base: 027ef400acd65280c4815a0490e61c7d408ec2a7b9374557587c18ffc29e1ddbb401b1f301efed627bfc67c210656753a0768381cd41e765100302ee773e7d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
