# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56cce5691e9b4d5ae164e0aac50239cc8ada3c5bb92ea788ef462d4a0d256dfcaa56a972e84c553676072bb2cf138250618e6bc62194736b914f0ec5f8fef72

test:
  secret_key_base: 82396d74948b988735c4f4f7716f01f2ba54d4c5cde8235d17e154adf3481ee7430ca073faeda03b84f8cc78270e07ddee87900a248522b8a3e52fc723464fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
