# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4afb71c52b6b1f4224621e162e52f1c7c0bf1a2d10f297f53535c572cfa1d23c448286623dd1b0594e79736df374cd33e9e224105dda503a98557c625651df2

test:
  secret_key_base: 2fbab397628d7c05683fd77c46bc8e5a2c342fbffb7af6a77dd8828fcc26fcd03cac7ab6fff66efa61869e382643c0de0cd9e4c672044f2ca67d877b93ffbe10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
